apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
    - name: ftp
      port: 21
      targetPort: 21
      protocol: TCP
    - name: pasv-min-port
      protocol: TCP
      port: 10100
      targetPort: 10100
    - name: pasv-max-port
      port: 10101
      targetPort: 10101
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.99.127
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - name: ftp
          containerPort: 21
        - name: pasv-min-port
          containerPort: 10100
        - name: pasv-max-port
          containerPort: 10101
        volumeMounts:
        - name: ftps-storage
          mountPath: /etc/ftps
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep vsftpd'
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: ftps-storage
        persistentVolumeClaim:
          claimName: ftps-mypvc
      restartPolicy: Always
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-mypvc
  labels:
    app: ftps
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
